//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartLabel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int PromotionKey { get; set; }
        public string PromotionName { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<double> DiscountRate { get; set; }
        public Nullable<double> DiscountPrice { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> ModifyBy { get; set; }
        public Nullable<byte> Active { get; set; }
        public string FileName { get; set; }
        public string PhysicalPath { get; set; }
        public string IISPath { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
